<table class="table table-hover" id="realops-flight-schedule">
  <thead>
    <tr>
      <th>Flight</th>
      <th>Type</th>
      <th>Origin</th>
      <th>STD</th>
      <th>Destination</th>
      <th>STA</th>
      <th>Status</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td>AM204</td>
      <td>BE20</td>
      <td>YSDU</td>
      <td>09:30</td>
      <td>YSSY</td>
      <td>10:45</td>
      <td>Available<br/>Book</td>
    </tr>
    <tr>
      <td>AM204</td>
      <td>BE20</td>
      <td>YSDU</td>
      <td>09:30</td>
      <td>YSSY</td>
      <td>10:45</td>
      <td>Available<br/>Book</td>
    </tr>
    <tr>
      <td>AM204</td>
      <td>BE20</td>
      <td>YSDU</td>
      <td>09:30</td>
      <td>YSSY</td>
      <td>10:45</td>
      <td>Available<br/>Book</td>
    </tr>
    <tr>
      <td>AM204</td>
      <td>BE20</td>
      <td>YSDU</td>
      <td>09:30</td>
      <td>YSSY</td>
      <td>10:45</td>
      <td>Available<br/>Book</td>
    </tr>
    <tr>
      <td>AM204</td>
      <td>BE20</td>
      <td>YSDU</td>
      <td>09:30</td>
      <td>YSSY</td>
      <td>10:45</td>
      <td>Available<br/>Book</td>
    </tr>
    <tr>
      <td>AM204</td>
      <td>BE20</td>
      <td>YSDU</td>
      <td>09:30</td>
      <td>YSSY</td>
      <td>10:45</td>
      <td>Available<br/>Book</td>
    </tr>
  </tbody>
</table>
